const
  { Settings block }
  // Server details
  SERVER_ADDRESS           = 'auth.activeworlds.com'; // Universe server address
  SERVER_PORT              = 6670;                    // Universe port
  SERVER_INSTANCE          = nil;                     // Universte instance
  // Login details
  CITIZEN_NUMBER           = 000000;               // Your citizen number
  LOGIN_APPLICATION_NAME   = 'Pascal DJ bot'; // Application name
  LOGIN_NAME               = 'Invisible DJ';       // Bot name (used in the chat)
  LOGIN_PRIVILEGE_PASSWORD = 'password';           // Your privilege password (Options -> Citizen - > Privilege password)
  // World details
  WORLD_NAME               = 'WildAW'; // World name to join
  // Bot details
  BOT_X_POS                = 1000; // X position (W-E)
  BOT_Z_POS                = 1000; // Y position (N-S)
  BOT_YAW                  = 2250; // YAW (rotation along Y-axis)
  // Misc
  FIVE_MINUTES             = (5 * 60 * 1000);
  SPEAKER_OBJECT           = 'midispk.rwx';
  { End settings block }